//
//  UpStyleKit.swift
//  Up
//
//  Created by David Taylor on 9/6/16.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class UpStyleKit : NSObject {

    //// Drawing Methods

    public class func drawUpIcon() {

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPoint(x: 30, y: 0))
        bezier2Path.addCurveToPoint(CGPoint(x: 39.82, y: 9.82), controlPoint1: CGPoint(x: 30, y: 0), controlPoint2: CGPoint(x: 34.4, y: 4.4))
        bezier2Path.addCurveToPoint(CGPoint(x: 40.33, y: 10.33), controlPoint1: CGPoint(x: 39.99, y: 9.99), controlPoint2: CGPoint(x: 40.16, y: 10.16))
        bezier2Path.addCurveToPoint(CGPoint(x: 45.88, y: 15.88), controlPoint1: CGPoint(x: 42.12, y: 12.12), controlPoint2: CGPoint(x: 44.01, y: 14.01))
        bezier2Path.addCurveToPoint(CGPoint(x: 60, y: 30), controlPoint1: CGPoint(x: 53.07, y: 23.08), controlPoint2: CGPoint(x: 60, y: 30))
        bezier2Path.addCurveToPoint(CGPoint(x: 33.75, y: 30), controlPoint1: CGPoint(x: 60, y: 30), controlPoint2: CGPoint(x: 41.8, y: 30.09))
        bezier2Path.addCurveToPoint(CGPoint(x: 33.75, y: 45), controlPoint1: CGPoint(x: 33.75, y: 34.86), controlPoint2: CGPoint(x: 33.75, y: 40.05))
        bezier2Path.addLineToPoint(CGPoint(x: 26.25, y: 45))
        bezier2Path.addCurveToPoint(CGPoint(x: 26.25, y: 29.71), controlPoint1: CGPoint(x: 26.25, y: 40.05), controlPoint2: CGPoint(x: 26.25, y: 34.56))
        bezier2Path.addCurveToPoint(CGPoint(x: 26.25, y: 24.11), controlPoint1: CGPoint(x: 26.25, y: 27.11), controlPoint2: CGPoint(x: 26.25, y: 25.1))
        bezier2Path.addCurveToPoint(CGPoint(x: 30, y: 24.03), controlPoint1: CGPoint(x: 28.4, y: 24.06), controlPoint2: CGPoint(x: 30, y: 24.03))
        bezier2Path.addLineToPoint(CGPoint(x: 45, y: 24.38))
        bezier2Path.addLineToPoint(CGPoint(x: 30, y: 9.38))
        bezier2Path.addLineToPoint(CGPoint(x: 15, y: 24.38))
        bezier2Path.addCurveToPoint(CGPoint(x: 18.75, y: 24.29), controlPoint1: CGPoint(x: 15, y: 24.38), controlPoint2: CGPoint(x: 16.6, y: 24.34))
        bezier2Path.addCurveToPoint(CGPoint(x: 18.75, y: 30), controlPoint1: CGPoint(x: 18.75, y: 25.34), controlPoint2: CGPoint(x: 18.75, y: 27.51))
        bezier2Path.addCurveToPoint(CGPoint(x: 0, y: 30), controlPoint1: CGPoint(x: 10.24, y: 30.1), controlPoint2: CGPoint(x: 0, y: 30))
        bezier2Path.addCurveToPoint(CGPoint(x: 16.66, y: 13.34), controlPoint1: CGPoint(x: 0, y: 30), controlPoint2: CGPoint(x: 8.65, y: 21.35))
        bezier2Path.addCurveToPoint(CGPoint(x: 29.99, y: 0.01), controlPoint1: CGPoint(x: 23.44, y: 6.56), controlPoint2: CGPoint(x: 29.76, y: 0.24))
        bezier2Path.addLineToPoint(CGPoint(x: 30, y: 0))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPoint(x: 33.75, y: 52.5))
        bezier2Path.addCurveToPoint(CGPoint(x: 33.75, y: 60), controlPoint1: CGPoint(x: 33.75, y: 56.97), controlPoint2: CGPoint(x: 33.75, y: 60))
        bezier2Path.addLineToPoint(CGPoint(x: 26.25, y: 60))
        bezier2Path.addCurveToPoint(CGPoint(x: 26.25, y: 52.5), controlPoint1: CGPoint(x: 26.25, y: 60), controlPoint2: CGPoint(x: 26.25, y: 56.97))
        bezier2Path.addLineToPoint(CGPoint(x: 33.75, y: 52.5))
        bezier2Path.closePath()
        UIColor.grayColor().setFill()
        bezier2Path.fill()
    }

    public class func drawTabBarIcons() {

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPoint(x: 12.5, y: 0))
        bezier2Path.addCurveToPoint(CGPoint(x: 16.59, y: 4.1), controlPoint1: CGPoint(x: 12.5, y: 0), controlPoint2: CGPoint(x: 14.33, y: 1.83))
        bezier2Path.addCurveToPoint(CGPoint(x: 16.8, y: 4.3), controlPoint1: CGPoint(x: 16.66, y: 4.16), controlPoint2: CGPoint(x: 16.73, y: 4.23))
        bezier2Path.addCurveToPoint(CGPoint(x: 19.12, y: 6.62), controlPoint1: CGPoint(x: 17.55, y: 5.05), controlPoint2: CGPoint(x: 18.34, y: 5.84))
        bezier2Path.addCurveToPoint(CGPoint(x: 25, y: 12.5), controlPoint1: CGPoint(x: 22.11, y: 9.62), controlPoint2: CGPoint(x: 25, y: 12.5))
        bezier2Path.addCurveToPoint(CGPoint(x: 14.06, y: 12.5), controlPoint1: CGPoint(x: 25, y: 12.5), controlPoint2: CGPoint(x: 17.42, y: 12.54))
        bezier2Path.addCurveToPoint(CGPoint(x: 14.06, y: 18.75), controlPoint1: CGPoint(x: 14.06, y: 14.53), controlPoint2: CGPoint(x: 14.06, y: 16.69))
        bezier2Path.addLineToPoint(CGPoint(x: 10.94, y: 18.75))
        bezier2Path.addCurveToPoint(CGPoint(x: 10.94, y: 12.38), controlPoint1: CGPoint(x: 10.94, y: 16.69), controlPoint2: CGPoint(x: 10.94, y: 14.4))
        bezier2Path.addCurveToPoint(CGPoint(x: 10.94, y: 10.05), controlPoint1: CGPoint(x: 10.94, y: 11.3), controlPoint2: CGPoint(x: 10.94, y: 10.46))
        bezier2Path.addCurveToPoint(CGPoint(x: 12.5, y: 10.01), controlPoint1: CGPoint(x: 11.83, y: 10.03), controlPoint2: CGPoint(x: 12.5, y: 10.01))
        bezier2Path.addLineToPoint(CGPoint(x: 18.75, y: 10.16))
        bezier2Path.addLineToPoint(CGPoint(x: 12.5, y: 3.91))
        bezier2Path.addLineToPoint(CGPoint(x: 6.25, y: 10.16))
        bezier2Path.addCurveToPoint(CGPoint(x: 7.81, y: 10.12), controlPoint1: CGPoint(x: 6.25, y: 10.16), controlPoint2: CGPoint(x: 6.92, y: 10.14))
        bezier2Path.addCurveToPoint(CGPoint(x: 7.81, y: 12.5), controlPoint1: CGPoint(x: 7.81, y: 10.56), controlPoint2: CGPoint(x: 7.81, y: 11.47))
        bezier2Path.addCurveToPoint(CGPoint(x: -0, y: 12.5), controlPoint1: CGPoint(x: 4.27, y: 12.54), controlPoint2: CGPoint(x: -0, y: 12.5))
        bezier2Path.addCurveToPoint(CGPoint(x: 6.94, y: 5.56), controlPoint1: CGPoint(x: -0, y: 12.5), controlPoint2: CGPoint(x: 3.6, y: 8.9))
        bezier2Path.addCurveToPoint(CGPoint(x: 12.5, y: 0), controlPoint1: CGPoint(x: 9.77, y: 2.74), controlPoint2: CGPoint(x: 12.4, y: 0.1))
        bezier2Path.addLineToPoint(CGPoint(x: 12.5, y: 0))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPoint(x: 14.06, y: 21.88))
        bezier2Path.addCurveToPoint(CGPoint(x: 14.06, y: 25), controlPoint1: CGPoint(x: 14.06, y: 23.74), controlPoint2: CGPoint(x: 14.06, y: 25))
        bezier2Path.addLineToPoint(CGPoint(x: 10.94, y: 25))
        bezier2Path.addCurveToPoint(CGPoint(x: 10.94, y: 21.88), controlPoint1: CGPoint(x: 10.94, y: 25), controlPoint2: CGPoint(x: 10.94, y: 23.74))
        bezier2Path.addLineToPoint(CGPoint(x: 14.06, y: 21.88))
        bezier2Path.closePath()
        UIColor.grayColor().setFill()
        bezier2Path.fill()
    }

}
